### ISSUE TITLE
mentions-to-indices not working

### ISSUE THREAD

**Issue by cfhaak** [acdh-oeaw/acdh-tei-pyutils#34]
running mentions-to-indices causes **doc.create_mention_list** to throw 
```
  File "$path/.venv/lib/python3.11/site-packages/acdh_tei_pyutils/cli.py", line 161, in mentions_to_indices
    event_list = doc.create_mention_list(mention, event_title=event_title)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TeiEnricher.create_mention_list() got an unexpected keyword argument 'event_title'
```
This is due to a bugfix regarding **denormalize_indices** where calling ```create_mention_list``` didn't require the ```event_title``` argument any longer. Possible fix would make the argument optional by adding a default val None with an extra check.

**Comment by cfhaak** [comment]
There are more errors, some caused by missing fields in dictionaries. While this is pretty easy to fix, wouldn't it be easier for maintenance and readability to use classes/objects to prevent this kind of errors?

**Comment by csae8092** [comment]
I'm not sure, because I'm using the denormalize indices for ages now and i never run into any issues; @linxOD may you PR have introduced the issues reported by @cfhaak 

@cfhaak could you point me please to the code causing troubles for you

**Comment by csae8092** [comment]
@cfhaak but feel free to improve the code quality by swap dicts with classes where feasible

**Comment by cfhaak** [comment]
sure
main issue occurs here: https://github.com/acdh-oeaw/acdh-tei-pyutils/blob/f94121144ec8523e73a5b61e2662fea27541728b/acdh_tei_pyutils/cli.py#L161
reasons are:'
xpath without nsmap
```
# ent_id = ent.xpath("@xml:id")[0]
ent_id = ent.xpath("@xml:id", namespaces=doc.nsmap)[0]
```
ref_doc_dict entries are missing keys/vals
```
ref_doc_dict[ref].append(
  # {"doc_uri": doc_uri, "doc_path": x, "doc_title": doc_title}
  {"doc_uri": doc_uri, "doc_path": x, "doc_title": doc_title, "doc_id": doc_id, "doc_date": None, "doc_title_sec": None}
)
```
[called function](https://github.com/acdh-oeaw/acdh-tei-pyutils/blob/f94121144ec8523e73a5b61e2662fea27541728b/acdh_tei_pyutils/tei.py#L248) didn't expect/handle argument, so I added it & created handling
```
def create_mention_list(self, mentions, event_title=""):
…
…
        if x['doc_title_sec'] is not None:
            # note.text = f"{x['doc_title']} {x['doc_title_sec']}"
            note.text = event_title + f"{x['doc_title']} {x['doc_title_sec']}"
```

**Comment by cfhaak** [comment]
On the long run, one could think about creating a mention-class which instances represent an entity and a list of its mentions, contain **all relevant data** per mention as fields and which handle the xml serialization on their own, via a function, returning xml. This could then be called by a loop iterating over the mention objects. But I don't know the code well enough, just a suggestion.

**Comment by cfhaak** [comment]
For now I would just try the above already suggested fixes, which don't interfere with the current structure.
